### ISSUE TITLE
Launch Check Now gives 500 Error

### ISSUE THREAD

**Issue by lukayeh** [tinyclues/saltpad#90] opened 2015-09-15 11:15 UTC
Hi, 

When launching check now from the minion status page we get a 500 error from the following URL:

http://salt.e4bh.services/job_result/20150915121038554667?minion=grimes.e4bh.internal&renderer=highstate

We are running:

````
[root@pepper salt]# salt --versions-report
           Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Jul 23 2015, 05:13:40)
         Jinja2: 2.8
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
````

````
salt-api 2015.5.3
````

Any ideas?

Thanks,

**Comment by Lothiraldan** [comment] 2015-09-15 12:40
Could you remove the `renderer=highstate` from the url?

**Comment by lukayeh** [comment] 2015-09-15 12:42
Hi @Lothiraldan 

I get the same 500 Internal Server Error response.

````
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
````

Thanks,

**Comment by lukayeh** [comment] 2015-09-22 09:34
Hi @Lothiraldan 

Did you get a chance to think about this?

Thanks,

**Comment by Lothiraldan** [comment] 2015-09-23 20:56
Hi @lukayeh, how do you launch saltpad? Is all your minion salt version up-to-date?

**Comment by lukayeh** [comment] 2015-09-24 10:12
Hi @Lothiraldan 

We are running it with chausette and nginx as advised in the docs, the command we're using in chausette is below:
````
chaussette --log-level DEBUG --log-output /var/log/chaussette/error.log saltpad.app:app
````
and nginx config is:
````
server {
    listen              443 ssl;
    server_name         salt.e4bh.services;
    ssl_certificate     /etc/pki/tls/certs/salt.e4bh.services.crt;
    ssl_certificate_key /etc/pki/tls/certs/salt.e4bh.services.key;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;


        location / {
            proxy_pass http://localhost:8080/;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
````


Thanks,

**Comment by Lothiraldan** [comment] 2015-09-24 11:37
Do you have any more information in /var/log/chaussette/error.log ?

**Comment by lukayeh** [comment] 2015-09-24 14:21
Hi @Lothiraldan 

There's nothing in there, apart from

````
2015-09-24 15:00:52 [2478] [INFO] Serving on localhost:8080
2015-09-24 15:00:52 [2478] [INFO] Using <class chaussette.backend._wsgiref.ChaussetteServer at 0x16f0050> as a backend
````
After you start the app.

Thanks,

**Comment by Lothiraldan** [comment] 2015-10-12 12:11
@lukayeh Sorry for the lag, could you give me the version of your minions please?

**Comment by lukayeh** [comment] 2015-10-28 15:09
@Lothiraldan 

Sorry for the lag on my end there!

salt-minion 2015.5.3 (Lithium)

Regards,

**Comment by lukayeh** [comment] 2015-10-30 14:57
Hi @Lothiraldan 

I set the master logs to debug incase its on the saltstack side of things and it looks like the call to highstate has worked correctly:
````
ternal': {'return': {'file_|-/etc/yum.repos.d/local-ol6.repo_|-/etc/yum.repos.d/local-ol6.repo_|-managed': {'comment': 'The file /etc/yum.repos.d/local-ol6.repo is in the correct state', 'name': '/etc/yum.repos.d/local-ol6.repo', 'start_time': '14:53:29.162058', 'result': True, 'duration': 19.934999999999999, '__run_num__': 0, 'changes': {}}}, 'out': 'highstate'}}, 'Target': 'itami.e4bh.internal', 'Target-type': 'glob', 'User': 'lpage', 'StartTime': '2015, Oct 30 14:53:28.610458', 'Minions': ['itami.e4bh.internal'], 'Arguments': [{'test': True, '__kwarg__': True}]}, 'success': True, '_stamp': '2015-10-30T14:53:30.221836', 'user': 'lpage', 'fun': 'runner.jobs.list_job'}
````

Also checked the nginx log and this was what it has

````

172.19.34.48 - - [30/Oct/2015:14:53:09 +0000] "GET / HTTP/1.1" 200 17749 "http://salt.e4bh.services/minions" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0" "-"
172.19.34.48 - - [30/Oct/2015:14:53:13 +0000] "GET /minions HTTP/1.1" 200 16149 "http://salt.e4bh.services/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0" "-"
172.19.34.48 - - [30/Oct/2015:14:53:28 +0000] "GET /minions/itami.e4bh.internal/do_check_sync HTTP/1.1" 302 371 "http://salt.e4bh.services/minions" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0" "-"
172.19.34.48 - - [30/Oct/2015:14:53:30 +0000] "GET /job_result/20151030145328610458?minion=itami.e4bh.internal&renderer=highstate HTTP/1.1" 500 291 "http://salt.e4bh.services/minions" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0" "-"
172.19.34.48 - - [30/Oct/2015:14:56:06 +0000] "GET /minions/itami.e4bh.internal/do_check_sync HTTP/1.1" 302 371 "http://salt.e4bh.services/minions" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0" "-"
172.19.34.48 - - [30/Oct/2015:14:56:08 +0000] "GET /job_result/20151030145606637876?minion=itami.e4bh.internal&renderer=highstate HTTP/1.1" 500 291 "http://salt.e4bh.services/minions" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0" "-"
````

**Comment by lukayeh** [comment] 2015-10-30 16:56
Hi @Lothiraldan 

We have also noticed this in the jobs page too :(

![2015-10-30 16_55_35-clipboard](https://cloud.githubusercontent.com/assets/12659390/10852151/260a52a4-7f27-11e5-8e7e-3ae365bc704c.png)

**Comment by Lothiraldan** [comment] 2015-11-04 22:51
I've no clues about what could possibly happens, could you try launching saltpad with the run command described here https://github.com/tinyclues/saltpad#for-testing-purpose?

Please be careful that the host should be different than 0.0.0.0 in settings, I've just commit a check that will raises you a big warning if you try to do that.

Please also change the port so saltpad wouldn't be exposed to the whole world through nginx unintentionally.

Now if you have access to saltpad without passing by nginx (I hope), just paste the traceback like in this other issue (https://github.com/tinyclues/saltpad/issues/91#issue-106863023). It shouldn't contains sensitive information but double-check the paste before in order to be sure.

**Comment by lukayeh** [comment] 2015-11-05 11:00
Hi @Lothiraldan 

I've ran saltpad locally and as have the trace below:

````
[root@pepper saltpad-master]# python run.py
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
127.0.0.1 - - [05/Nov/2015 10:47:12] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Nov/2015 10:47:43] "GET /minions HTTP/1.1" 200 -
127.0.0.1 - - [05/Nov/2015 10:48:53] "GET /minions/itami.e4bh.internal/do_check_sync HTTP/1.1" 302 -
127.0.0.1 - - [05/Nov/2015 10:48:54] "GET /job_result/20151105104853603406?minion=itami.e4bh.internal&renderer=highstate HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/saltpad-master/saltpad/app.py", line 63, in wrapper
    return view(*args, **kwargs)
  File "/root/saltpad-master/saltpad/app.py", line 200, in job_result
    renderer=renderer)
  File "/usr/lib/python2.6/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/lib/python2.6/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/lib/python2.6/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.6/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/saltpad-master/saltpad/templates/job_result_highstate.html", line 2, in top-level template code
    {% extends "job_result.html" %}
  File "/root/saltpad-master/saltpad/templates/job_result.html", line 2, in top-level template code
    {% extends "base_logged.html" %}
  File "/root/saltpad-master/saltpad/templates/base_logged.html", line 2, in top-level template code
    {% from "macros.jinja" import print_flash_messages %}
  File "/root/saltpad-master/saltpad/templates/base.html", line 26, in top-level template code
    {% block body %}
  File "/root/saltpad-master/saltpad/templates/base_logged.html", line 123, in block "body"
    {% block page %}
  File "/root/saltpad-master/saltpad/templates/job_result.html", line 9, in block "page"
    <h1>{{ job.info.Function }} on {{ job.info.Target }} started at {{ job.info.StartTime }} by {{ job.info.User }} <small>Arguments {{ job.info.Arguments|format_arguments }}  <a href="{{ url_for('redo_job', jid=job.info.jid, minion=minion, renderer=renderer) }}"><button class="btn btn-primary btn-sm"><i class="fa fa-refresh"></i> Redo job with same parameters</button></a></small> </h1>
  File "/root/saltpad-master/saltpad/app.py", line 442, in format_argument
    return " ".join(format_arguments(arguments))
  File "/root/saltpad-master/saltpad/utils.py", line 193, in format_arguments
    yield "--{}={}".format(*list(argument.items())[0])
ValueError: zero length field name in format
127.0.0.1 - - [05/Nov/2015 10:48:55] "GET /job_result/20151105104853603406?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [05/Nov/2015 10:48:55] "GET /job_result/20151105104853603406?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [05/Nov/2015 10:48:55] "GET /job_result/20151105104853603406?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [05/Nov/2015 10:48:55] "GET /job_result/20151105104853603406?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [05/Nov/2015 10:48:55] "GET /job_result/20151105104853603406?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [05/Nov/2015 10:48:55] "GET /job_result/20151105104853603406?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [05/Nov/2015 10:48:55] "GET /job_result/20151105104853603406?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
````
![2015-11-05 10_59_49-clipboard](https://cloud.githubusercontent.com/assets/12659390/10966579/5e0864e6-83ac-11e5-80aa-9d6b6352cd87.png)

So the error message looks to be different when running locally which is nice!

Any ideas?

I also pulled your change you recommended on the issue you pointed me to and it didn't make a difference.

Thanks,

**Comment by lukayeh** [comment] 2015-11-05 14:12
On looks at the error it appears to be a limitation with python 2.6 unfortunately because we are using Oracle Linux 6 we are limited to only this version as its the highest we can get from the repo.

Regards,

**Comment by Lothiraldan** [comment] 2015-11-05 14:14
I will try to push a fix for this problem tonight (~6 hours in this time-zone), stay tined

**Comment by Lothiraldan** [comment] 2015-11-05 22:28
I just pushed a PR which should fix the problem https://github.com/tinyclues/saltpad/pull/93, could you pull the corresponding branch `90-fix` and validate the fix?

**Comment by lukayeh** [comment] 2015-11-09 09:58
Hi @Lothiraldan 

That appears to have fixed the issue however in the home dashboard the minions in sync is getting updated is this a expected outcome:

![2015-11-09 09_47_05-clipboard](https://cloud.githubusercontent.com/assets/12659390/11030727/d3b4ae3e-86c7-11e5-8781-05f56843c19a.png)

Also we see the following when selecting aggregate results from the job history page:

![2015-11-09 09_57_19-clipboard](https://cloud.githubusercontent.com/assets/12659390/11030805/4f2c5b98-86c8-11e5-8d6d-07c176e6a0ff.png)


````
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
127.0.0.1 - - [09/Nov/2015 09:55:16] "GET /login?next=%2F HTTP/1.1" 200 -
127.0.0.1 - - [09/Nov/2015 09:55:16] "GET /static/css/bootstrap.css HTTP/1.1" 30                                                                                                                                                             4 -
127.0.0.1 - - [09/Nov/2015 09:55:16] "GET /static/css/sb-admin.css HTTP/1.1" 304                                                                                                                                                              -
127.0.0.1 - - [09/Nov/2015 09:55:16] "GET /static/font-awesome/css/font-awesome.                                                                                                                                                             min.css HTTP/1.1" 304 -
127.0.0.1 - - [09/Nov/2015 09:55:16] "GET /static/css/saltpad.css HTTP/1.1" 304                                                                                                                                                              -
127.0.0.1 - - [09/Nov/2015 09:55:16] "GET /static/css/jsontree.css HTTP/1.1" 304                                                                                                                                                              -
127.0.0.1 - - [09/Nov/2015 09:55:16] "GET /static/css/dataTables.bootstrap.css H                                                                                                                                                             TTP/1.1" 304 -
127.0.0.1 - - [09/Nov/2015 09:55:16] "GET /static/js/jquery-1.10.2.js HTTP/1.1"                                                                                                                                                              304 -
127.0.0.1 - - [09/Nov/2015 09:55:16] "GET /static/js/bootstrap.js HTTP/1.1" 304                                                                                                                                                              -
127.0.0.1 - - [09/Nov/2015 09:55:16] "GET /static/js/jsontree.js HTTP/1.1" 304 -
127.0.0.1 - - [09/Nov/2015 09:55:16] "GET /static/js/jquery.dataTables.min.js HT                                                                                                                                                             TP/1.1" 304 -
127.0.0.1 - - [09/Nov/2015 09:55:16] "GET /static/js/dataTables.bootstrap.js HTT                                                                                                                                                             P/1.1" 304 -
127.0.0.1 - - [09/Nov/2015 09:55:17] "GET /static/font-awesome/fonts/fontawesome                                                                                                                                                             -webfont.woff?v=4.2.0 HTTP/1.1" 304 -
127.0.0.1 - - [09/Nov/2015 09:55:17] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [09/Nov/2015 09:55:21] "POST /login?next=%2F HTTP/1.1" 302 -
127.0.0.1 - - [09/Nov/2015 09:55:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [09/Nov/2015 09:55:33] "GET /jobs HTTP/1.1" 200 -
127.0.0.1 - - [09/Nov/2015 09:55:33] "GET /static/images/sort_both.png HTTP/1.1"                                                                                                                                                              304 -
127.0.0.1 - - [09/Nov/2015 09:55:34] "GET /static/images/sort_desc.png HTTP/1.1"                                                                                                                                                              304 -
127.0.0.1 - - [09/Nov/2015 09:55:38] "GET /job_result/20151109095524832523?rende                                                                                                                                                             rer=raw HTTP/1.1" 200 -
127.0.0.1 - - [09/Nov/2015 09:55:41] "GET /job_result/20151109095524832523?rende                                                                                                                                                             rer=aggregate HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1403, in handle_exc                                                                                                                                                             eption
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispa                                                                                                                                                             tch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_use                                                                                                                                                             r_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispa                                                                                                                                                             tch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_r                                                                                                                                                             equest
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/saltpad-master/saltpad/app.py", line 63, in wrapper
    return view(*args, **kwargs)
  File "/root/saltpad-master/saltpad/app.py", line 200, in job_result
    renderer=renderer)
  File "/usr/lib/python2.6/site-packages/flask/templating.py", line 128, in rend                                                                                                                                                             er_template
    context, ctx.app)
  File "/usr/lib/python2.6/site-packages/flask/templating.py", line 110, in _ren                                                                                                                                                             der
    rv = template.render(context)
  File "/usr/lib/python2.6/site-packages/jinja2/environment.py", line 989, in re                                                                                                                                                             nder
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.6/site-packages/jinja2/environment.py", line 754, in ha                                                                                                                                                             ndle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/saltpad-master/saltpad/templates/job_result_aggregate.html", line                                                                                                                                                              1, in top-level template code
    {% extends "job_result.html" %}
  File "/root/saltpad-master/saltpad/templates/job_result.html", line 2, in top-                                                                                                                                                             level template code
    {% extends "base_logged.html" %}
  File "/root/saltpad-master/saltpad/templates/base_logged.html", line 2, in top                                                                                                                                                             -level template code
    {% from "macros.jinja" import print_flash_messages %}
  File "/root/saltpad-master/saltpad/templates/base.html", line 26, in top-level                                                                                                                                                              template code
    {% block body %}
  File "/root/saltpad-master/saltpad/templates/base_logged.html", line 123, in b                                                                                                                                                             lock "body"
    {% block page %}
  File "/root/saltpad-master/saltpad/templates/job_result.html", line 47, in blo                                                                                                                                                             ck "page"
    {% block job_result %}
  File "/root/saltpad-master/saltpad/templates/job_result_aggregate.html", line                                                                                                                                                              18, in block "job_result"
    <h3>{{hiding_control('hide_control_minion', True)|safe }} {{ minions|length                                                                                                                                                              }} ({{ '{:.0%}'.format(minions|length / total_minions_length) }}) minion(s) with                                                                                                                                                              this result:</h3>
ZeroDivisionError: float division
127.0.0.1 - - [09/Nov/2015 09:55:41] "GET /job_result/20151109095524832523?__deb                                                                                                                                                             ugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [09/Nov/2015 09:55:41] "GET /job_result/20151109095524832523?__deb                                                                                                                                                             ugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Nov/2015 09:55:41] "GET /job_result/20151109095524832523?__deb                                                                                                                                                             ugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Nov/2015 09:55:41] "GET /job_result/20151109095524832523?__deb                                                                                                                                                             ugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [09/Nov/2015 09:55:42] "GET /job_result/20151109095524832523?__deb                                                                                                                                                             ugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [09/Nov/2015 09:55:42] "GET /job_result/20151109095524832523?__deb                                                                                                                                                             ugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [09/Nov/2015 09:55:42] "GET /job_result/20151109095524832523?__deb                                                                                                                                                             ugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -

````

**Comment by Lothiraldan** [comment] 2015-11-09 10:45
The minions in sync counter is not working right now, it's working on SaltPad V2 I'm working on.

About the other error, I think it may be caused by a job which didn't match any minion, will try a quick-fix for this situation.

Please be advised that the current version of saltpad (master branch) is mostly working but presents some quirks in scenarios I didn't encounter myself, I'm trying to make a more stable and user-friendly version of saltpad right now, so all the views may not be perfectly functioning.

**Comment by lukayeh** [comment] 2015-11-09 11:02
Hi @Lothiraldan 

No worries :+1:  I look forward to V2!

Thanks,

**Comment by Lothiraldan** [comment] 2015-11-09 19:55
Could you give me the value of theses config keys:
- netapi (rest_cherrypy or rest_tornado)
- ext_job_cache
- master_job_cache

**Comment by Lothiraldan** [comment] 2015-11-10 08:36
I couldn't find the exact root of the problem could you paste the "raw" (without ?renderer in url) reporting page of this job if it doesn't contains any sensitive information.

Does the problem also happens on other jobs?

**Comment by Lothiraldan** [comment] 2015-11-10 09:17
I pushed another fix for you problem in the same branch `fix-90` could you give it a try?

**Comment by lukayeh** [comment] 2015-11-10 09:34
Hi @Lothiraldan 

That appears to have fixed the issue :+1:  

When are you planning for v2 to be available?

**Comment by Lothiraldan** [comment] 2015-11-10 09:37
I will try to release a first alpha very soon (maybe this week), I'm still struggling to make the job run page working like I want.

About your job, would it be possible to forward me its "raw" result, I still cannot identify in which case it may happens.

**Comment by lukayeh** [comment] 2015-11-10 09:53
Hi @Lothiraldan 

I tried looking back for the job ID but can't seem to find it in my job history, it was occurring on all jobs when selecting aggregate results if that helps?

Thanks

**Comment by Lothiraldan** [comment] 2015-11-10 09:56
Yes, in that case, could you go back on master or this commit `f9262bcab451b79ef33bae6d101a5d8f35b2cb71` (`git checkout f9262bcab451b79ef33bae6d101a5d8f35b2cb71`) and paste me (or send by email) the result of an innocent job that fails (like test.ping)?

**Comment by lukayeh** [comment] 2015-11-10 12:21
Hi @Lothiraldan 

Not sure if this is what your after when you say 'raw' but the following is the result page for a test.ping that then errors when selecting Aggregate Results

![2015-11-10 12_19_27-clipboard](https://cloud.githubusercontent.com/assets/12659390/11062285/88f6bf48-87a5-11e5-9fc0-85d65671f4c6.png)

**Comment by Lothiraldan** [comment] 2015-11-10 13:06
It's very weird, I couldn't see why it could fails in aggregate Results page, anyway I will merge the PR so you will be able to use master branch now.

**Comment by lukayeh** [comment] 2015-11-10 13:07
Yeah I did have a poke around but way beyond my knowledge!

Thanks for your help on this one

**Closed** 2015-11-10 13:07 UTC

**Comment by Lothiraldan** [comment] 2015-11-10 13:09
Always a pleasure! If you want to drop me an email about your usage of saltpad, the size of your cluster, your specifics needs, don't hesitate! I will maybe opens a ticket about V2 discussion too

**Comment by lukayeh** [comment] 2016-06-06 12:25
Hi @Lothiraldan 

I know you're not developing much on this version now however, we're receiving a similar error to this one when checking the job history of a scheduled highstate.

When it goes to the following URL:
https://salt.e4bh.services/job_result/20160605235926480591?renderer=highstate

It'll cause a 500 error however if we change highstate to RAW it'll work fine.

If we run a check minion status the highstate renderer works fine.

Other scheduled jobs work fine it's just highstate. Very Odd.

Any ideas?

Regards,
