### ISSUE TITLE
Cannot auth using group membership pam external auth

### ISSUE THREAD

**Issue by jollyroger** [tinyclues/saltpad#54] opened 2015-05-07 07:03 UTC
Hi, I cannot authenticate using group membership in pam external auth but still able to auth if user is set directly in salt config. Here's example setup:

<pre>external_auth:
  pam:
    saltpad%:
      - .*
      - '@runner'
      - '@wheel'
    user1:
      - .*
      - '@runner'
      - '@wheel'
    user4:
      - .*
      - '@runner'
      - '@wheel'
</pre>

UNIX group called `saltpad` was created and has `user1` and `user2` as its members. There's also `user3` and `user4` that are not members of the `saltpad` group. I can authenticate with `user1`, `user2` and `user4` using salt command for example:

    $ salt -a pam \* test.ping
    [WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/master?
    username: user1
    password: 
    server1.example.com:
        True
    $ salt -a pam \* test.ping
    [WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/master?
    username: user2
    password: 
    server1.example.com:
        True
    $ salt -a pam \* test.ping
    [WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/master?
    username: user3
    password: 
    Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).

So, pam auth grants access for `user1`, `user2` and `user4` and deny access for `user3` as expected. However, when trying to log in saltpad, only `user1` and `user4` are granted access although `user2` is expected to log in as well (which isn't).

Software versions: 
 * saltpad: ef87633b, master branch
 * OS, Debian wheezy
 * salt, salt-api:2014.7.2+ds-1~bpo70+1 from http://debian.saltstack.com/debian

**Comment by Lothiraldan** [comment] 2015-05-07 08:58
Hi @jollyroger, I'm don't know if group authentication works trough salt-api, I will add a bit of doc to debug the authentication on salt-api side.

**Comment by Lothiraldan** [comment] 2015-05-07 14:59
I just added a debug doc for login issues, could you try to see if the issue comes from salt-api or saltpad using informations available here https://github.com/tinyclues/saltpad/blob/master/docs/debug.md?

**Comment by jollyroger** [comment] 2015-05-07 18:29
Thank you. I've got 401 Unauthorized for `user2`. So it seems it's not saltpad's fault. Thank you for help.

**Comment by jollyroger** [comment] 2015-05-07 18:38
It seems I've bumped into https://github.com/saltstack/salt/issues/17380

**Comment by Lothiraldan** [comment] 2015-05-07 18:42
Don't hesitate to leave a comment including your config, the curl command you used and the output, I'm sure they will be able to find the root cause of this problem.

If everything is fine, could you please close the issue? I try an experimentation where only the issue author should close the issue.

**Closed** 2015-05-08 07:10 UTC

**Comment by barryib** [comment] 2015-07-03 16:24
Hi, @Lothiraldan I used your debug doc and I got a successful login. I'm using these following versions:
 - salt-master 2015.5.2 (Lithium)
 - salt-api 2015.5.2

My configuration is like this:
````
external_auth:
  pam:
    admin%:
      - .*
      - '@runner'
      - '@wheel'
    user1:
      - .*
      - '@runner'
      - '@wheel'
````
- Login through salt-api with you debug tip:
  - admin_user: OK
  - user1: OK
- Login through saltpad:
  - admin_user: **KO**
  - user1: OK

**Comment by Lothiraldan** [comment] 2015-07-05 20:30
Hi @barryib, do you have any messages from saltpad or just a 500 page?

**Comment by barryib** [comment] 2015-07-06 07:42
Hello @Lothiraldan I get an 500 page from saltpad with this [error](https://gist.github.com/barryib/0f62d390920ada6b3d41).
For debug, here is the salt-api [traceback](https://gist.github.com/barryib/4d4f50762f4f7ab4319f).

**Comment by Lothiraldan** [comment] 2015-07-06 09:05
@barryib The issue seems to be not on login page but on the dashboard page where you are redirected after login, I don't know why but I will investigate.

You can use saltpad but going to "https://SALTPAD/minions_keys" to start playing with saltpad if you want.

**Comment by barryib** [comment] 2015-07-06 12:31
@Lothiraldan It doesn't work. I'm actually using saltpad without group membership
